"""add scheduler tick details

Revision ID: 402d89abbadc
Revises: e999b661f186
Create Date: 2022-09-04 21:42:03.945484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402d89abbadc'
down_revision = 'e999b661f186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_ticks', sa.Column('effectively_ran_at', sa.DateTime(), nullable=True))
    op.add_column('scheduler_ticks', sa.Column('ran_until', sa.DateTime(), nullable=True))
    op.add_column('scheduler_ticks', sa.Column('hook_id', sa.String(), nullable=True))
    op.add_column('scheduler_ticks', sa.Column('hit_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scheduler_ticks', 'hooks', ['hook_id'], ['id'])
    op.create_foreign_key(None, 'scheduler_ticks', 'hits', ['hit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduler_ticks', type_='foreignkey')
    op.drop_constraint(None, 'scheduler_ticks', type_='foreignkey')
    op.drop_column('scheduler_ticks', 'hit_id')
    op.drop_column('scheduler_ticks', 'hook_id')
    op.drop_column('scheduler_ticks', 'ran_until')
    op.drop_column('scheduler_ticks', 'effectively_ran_at')
    # ### end Alembic commands ###
