"""delete on cascade

Revision ID: 58fc59f8c336
Revises: 7727210c22ee
Create Date: 2022-09-17 16:24:36.082122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fc59f8c336'
down_revision = '7727210c22ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hits_hook_id_fkey', 'hits', type_='foreignkey')
    op.create_foreign_key(None, 'hits', 'hooks', ['hook_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('runs_hit_id_fkey', 'runs', type_='foreignkey')
    op.drop_constraint('runs_hook_id_fkey', 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'hooks', ['hook_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'runs', 'hits', ['hit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key('runs_hook_id_fkey', 'runs', 'hooks', ['hook_id'], ['id'])
    op.create_foreign_key('runs_hit_id_fkey', 'runs', 'hits', ['hit_id'], ['id'])
    op.drop_constraint(None, 'hits', type_='foreignkey')
    op.create_foreign_key('hits_hook_id_fkey', 'hits', 'hooks', ['hook_id'], ['id'])
    # ### end Alembic commands ###
