"""make status int

Revision ID: 7727210c22ee
Revises: 402d89abbadc
Create Date: 2022-09-08 12:31:28.200253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7727210c22ee'
down_revision = '402d89abbadc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_ticks')
    op.alter_column('hits', 'response_status', type_=sa.INTEGER, postgresql_using="response_status::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_ticks',
    sa.Column('id', sa.VARCHAR(), server_default=sa.text('generate_ulid()'), autoincrement=False, nullable=False),
    sa.Column('tick', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('effectively_ran_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ran_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hook_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hit_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hit_id'], ['hits.id'], name='scheduler_ticks_hit_id_fkey'),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], name='scheduler_ticks_hook_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheduler_ticks_pkey')
    )
    op.alter_column('hits', 'response_status', type_=sa.VARCHAR)
    # ### end Alembic commands ###
