"""first migration

Revision ID: e999b661f186
Revises: 
Create Date: 2022-09-04 21:28:29.906574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e999b661f186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute("""
        CREATE EXTENSION IF NOT EXISTS pgcrypto;

        CREATE FUNCTION generate_ulid()
        RETURNS TEXT
        AS $$
        DECLARE
          encoding   BYTEA = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
          timestamp  BYTEA = E'\\\\000\\\\000\\\\000\\\\000\\\\000\\\\000';
          output     TEXT = '';

          unix_time  BIGINT;
          ulid       BYTEA;
        BEGIN
          -- 6 timestamp bytes
          unix_time = (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT;
          timestamp = SET_BYTE(timestamp, 0, (unix_time >> 40)::BIT(8)::INTEGER);
          timestamp = SET_BYTE(timestamp, 1, (unix_time >> 32)::BIT(8)::INTEGER);
          timestamp = SET_BYTE(timestamp, 2, (unix_time >> 24)::BIT(8)::INTEGER);
          timestamp = SET_BYTE(timestamp, 3, (unix_time >> 16)::BIT(8)::INTEGER);
          timestamp = SET_BYTE(timestamp, 4, (unix_time >> 8)::BIT(8)::INTEGER);
          timestamp = SET_BYTE(timestamp, 5, unix_time::BIT(8)::INTEGER);

          -- 10 entropy bytes
          ulid = timestamp || gen_random_bytes(10);

          -- Encode the timestamp
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 0) & 224) >> 5));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 0) & 31)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 1) & 248) >> 3));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 1) & 7) << 2) | ((GET_BYTE(ulid, 2) & 192) >> 6)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 2) & 62) >> 1));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 2) & 1) << 4) | ((GET_BYTE(ulid, 3) & 240) >> 4)));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 3) & 15) << 1) | ((GET_BYTE(ulid, 4) & 128) >> 7)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 4) & 124) >> 2));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 4) & 3) << 3) | ((GET_BYTE(ulid, 5) & 224) >> 5)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 5) & 31)));

          -- Encode the entropy
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 6) & 248) >> 3));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 6) & 7) << 2) | ((GET_BYTE(ulid, 7) & 192) >> 6)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 7) & 62) >> 1));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 7) & 1) << 4) | ((GET_BYTE(ulid, 8) & 240) >> 4)));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 8) & 15) << 1) | ((GET_BYTE(ulid, 9) & 128) >> 7)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 9) & 124) >> 2));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 9) & 3) << 3) | ((GET_BYTE(ulid, 10) & 224) >> 5)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 10) & 31)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 11) & 248) >> 3));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 11) & 7) << 2) | ((GET_BYTE(ulid, 12) & 192) >> 6)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 12) & 62) >> 1));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 12) & 1) << 4) | ((GET_BYTE(ulid, 13) & 240) >> 4)));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 13) & 15) << 1) | ((GET_BYTE(ulid, 14) & 128) >> 7)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 14) & 124) >> 2));
          output = output || CHR(GET_BYTE(encoding, ((GET_BYTE(ulid, 14) & 3) << 3) | ((GET_BYTE(ulid, 15) & 224) >> 5)));
          output = output || CHR(GET_BYTE(encoding, (GET_BYTE(ulid, 15) & 31)));

          RETURN output;
        END
        $$
        LANGUAGE plpgsql
        VOLATILE;""")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_ticks',
    sa.Column('id', sa.String(), server_default=sa.text('generate_ulid()'), nullable=False),
    sa.Column('tick', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('wants_product_updates', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('hooks',
    sa.Column('id', sa.String(), server_default=sa.text('generate_ulid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('method', postgresql.ENUM('GET', 'POST', name='hookmethods'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('cron', sa.String(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_hit', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hits',
    sa.Column('id', sa.String(), server_default=sa.text('generate_ulid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('hook_id', sa.String(), nullable=True),
    sa.Column('response_status', sa.String(), nullable=True),
    sa.Column('response_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), server_default=sa.text('generate_ulid()'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('effectively_ran_at', sa.DateTime(), nullable=True),
    sa.Column('ran_until', sa.DateTime(), nullable=True),
    sa.Column('hook_id', sa.String(), nullable=True),
    sa.Column('hit_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hit_id'], ['hits.id'], ),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('hits')
    op.drop_table('hooks')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('scheduler_ticks')
    # ### end Alembic commands ###
    conn = op.get_bind()
    conn.execute("""drop function generate_ulid();""")

