"""first migration

Revision ID: 93efb7b0dbde
Revises: 
Create Date: 2022-10-04 09:22:22.166057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93efb7b0dbde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('wants_product_updates', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('hooks',
    sa.Column('id', sa.String(), server_default=sa.text('generate_ulid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('method', postgresql.ENUM('GET', 'POST', name='hookmethods'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('cron', sa.String(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_hit', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hits',
    sa.Column('id', sa.String(), server_default=sa.text('generate_ulid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('hook_id', sa.String(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), server_default=sa.text('generate_ulid()'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('effectively_ran_at', sa.DateTime(), nullable=True),
    sa.Column('ran_until', sa.DateTime(), nullable=True),
    sa.Column('hook_id', sa.String(), nullable=True),
    sa.Column('hit_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hit_id'], ['hits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('hits')
    op.drop_table('hooks')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
